rbac:
  create: true
controller:
  config:
    ssl-redirect: "false"
  scope:
    enabled: true
    namespace: 
  publishService:
    enabled: true
  service:
    targetPorts:
      http: http
      https: http
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "*.ayman.ps.dev.alfresco.me"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
